egress:
  proxy:
    url: ${FORGE_EGRESS_PROXY_URL:http://localhost:7072}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
